//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factura.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Factura.ServiceReference1.HelloWorldResponse HelloWorld(Factura.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Factura.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Factura.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento op1Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/op1", ReplyAction="*")]
        Factura.ServiceReference1.op1Response op1(Factura.ServiceReference1.op1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/op1", ReplyAction="*")]
        System.Threading.Tasks.Task<Factura.ServiceReference1.op1Response> op1Async(Factura.ServiceReference1.op1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Persona", ReplyAction="*")]
        Factura.ServiceReference1.PersonaResponse Persona(Factura.ServiceReference1.PersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Persona", ReplyAction="*")]
        System.Threading.Tasks.Task<Factura.ServiceReference1.PersonaResponse> PersonaAsync(Factura.ServiceReference1.PersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Puesto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargo", ReplyAction="*")]
        Factura.ServiceReference1.cargoResponse cargo(Factura.ServiceReference1.cargoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargo", ReplyAction="*")]
        System.Threading.Tasks.Task<Factura.ServiceReference1.cargoResponse> cargoAsync(Factura.ServiceReference1.cargoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Factura.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Factura.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class op1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="op1", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.op1RequestBody Body;
        
        public op1Request() {
        }
        
        public op1Request(Factura.ServiceReference1.op1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class op1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sueldo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int domingos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int fallas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int horasext;
        
        public op1RequestBody() {
        }
        
        public op1RequestBody(int sueldo, int domingos, int fallas, int horasext) {
            this.sueldo = sueldo;
            this.domingos = domingos;
            this.fallas = fallas;
            this.horasext = horasext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class op1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="op1Response", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.op1ResponseBody Body;
        
        public op1Response() {
        }
        
        public op1Response(Factura.ServiceReference1.op1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class op1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string op1Result;
        
        public op1ResponseBody() {
        }
        
        public op1ResponseBody(string op1Result) {
            this.op1Result = op1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Persona", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.PersonaRequestBody Body;
        
        public PersonaRequest() {
        }
        
        public PersonaRequest(Factura.ServiceReference1.PersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidos;
        
        public PersonaRequestBody() {
        }
        
        public PersonaRequestBody(string nombre, string apellidos) {
            this.nombre = nombre;
            this.apellidos = apellidos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.PersonaResponseBody Body;
        
        public PersonaResponse() {
        }
        
        public PersonaResponse(Factura.ServiceReference1.PersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PersonaResult;
        
        public PersonaResponseBody() {
        }
        
        public PersonaResponseBody(string PersonaResult) {
            this.PersonaResult = PersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargo", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.cargoRequestBody Body;
        
        public cargoRequest() {
        }
        
        public cargoRequest(Factura.ServiceReference1.cargoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Puesto;
        
        public cargoRequestBody() {
        }
        
        public cargoRequestBody(string Puesto) {
            this.Puesto = Puesto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Factura.ServiceReference1.cargoResponseBody Body;
        
        public cargoResponse() {
        }
        
        public cargoResponse(Factura.ServiceReference1.cargoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cargoResult;
        
        public cargoResponseBody() {
        }
        
        public cargoResponseBody(string cargoResult) {
            this.cargoResult = cargoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Factura.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Factura.ServiceReference1.WebService1Soap>, Factura.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Factura.ServiceReference1.HelloWorldResponse Factura.ServiceReference1.WebService1Soap.HelloWorld(Factura.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Factura.ServiceReference1.HelloWorldRequest inValue = new Factura.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Factura.ServiceReference1.HelloWorldRequestBody();
            Factura.ServiceReference1.HelloWorldResponse retVal = ((Factura.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Factura.ServiceReference1.HelloWorldResponse> Factura.ServiceReference1.WebService1Soap.HelloWorldAsync(Factura.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Factura.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Factura.ServiceReference1.HelloWorldRequest inValue = new Factura.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Factura.ServiceReference1.HelloWorldRequestBody();
            return ((Factura.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Factura.ServiceReference1.op1Response Factura.ServiceReference1.WebService1Soap.op1(Factura.ServiceReference1.op1Request request) {
            return base.Channel.op1(request);
        }
        
        public string op1(int sueldo, int domingos, int fallas, int horasext) {
            Factura.ServiceReference1.op1Request inValue = new Factura.ServiceReference1.op1Request();
            inValue.Body = new Factura.ServiceReference1.op1RequestBody();
            inValue.Body.sueldo = sueldo;
            inValue.Body.domingos = domingos;
            inValue.Body.fallas = fallas;
            inValue.Body.horasext = horasext;
            Factura.ServiceReference1.op1Response retVal = ((Factura.ServiceReference1.WebService1Soap)(this)).op1(inValue);
            return retVal.Body.op1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Factura.ServiceReference1.op1Response> Factura.ServiceReference1.WebService1Soap.op1Async(Factura.ServiceReference1.op1Request request) {
            return base.Channel.op1Async(request);
        }
        
        public System.Threading.Tasks.Task<Factura.ServiceReference1.op1Response> op1Async(int sueldo, int domingos, int fallas, int horasext) {
            Factura.ServiceReference1.op1Request inValue = new Factura.ServiceReference1.op1Request();
            inValue.Body = new Factura.ServiceReference1.op1RequestBody();
            inValue.Body.sueldo = sueldo;
            inValue.Body.domingos = domingos;
            inValue.Body.fallas = fallas;
            inValue.Body.horasext = horasext;
            return ((Factura.ServiceReference1.WebService1Soap)(this)).op1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Factura.ServiceReference1.PersonaResponse Factura.ServiceReference1.WebService1Soap.Persona(Factura.ServiceReference1.PersonaRequest request) {
            return base.Channel.Persona(request);
        }
        
        public string Persona(string nombre, string apellidos) {
            Factura.ServiceReference1.PersonaRequest inValue = new Factura.ServiceReference1.PersonaRequest();
            inValue.Body = new Factura.ServiceReference1.PersonaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellidos = apellidos;
            Factura.ServiceReference1.PersonaResponse retVal = ((Factura.ServiceReference1.WebService1Soap)(this)).Persona(inValue);
            return retVal.Body.PersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Factura.ServiceReference1.PersonaResponse> Factura.ServiceReference1.WebService1Soap.PersonaAsync(Factura.ServiceReference1.PersonaRequest request) {
            return base.Channel.PersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Factura.ServiceReference1.PersonaResponse> PersonaAsync(string nombre, string apellidos) {
            Factura.ServiceReference1.PersonaRequest inValue = new Factura.ServiceReference1.PersonaRequest();
            inValue.Body = new Factura.ServiceReference1.PersonaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellidos = apellidos;
            return ((Factura.ServiceReference1.WebService1Soap)(this)).PersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Factura.ServiceReference1.cargoResponse Factura.ServiceReference1.WebService1Soap.cargo(Factura.ServiceReference1.cargoRequest request) {
            return base.Channel.cargo(request);
        }
        
        public string cargo(string Puesto) {
            Factura.ServiceReference1.cargoRequest inValue = new Factura.ServiceReference1.cargoRequest();
            inValue.Body = new Factura.ServiceReference1.cargoRequestBody();
            inValue.Body.Puesto = Puesto;
            Factura.ServiceReference1.cargoResponse retVal = ((Factura.ServiceReference1.WebService1Soap)(this)).cargo(inValue);
            return retVal.Body.cargoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Factura.ServiceReference1.cargoResponse> Factura.ServiceReference1.WebService1Soap.cargoAsync(Factura.ServiceReference1.cargoRequest request) {
            return base.Channel.cargoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Factura.ServiceReference1.cargoResponse> cargoAsync(string Puesto) {
            Factura.ServiceReference1.cargoRequest inValue = new Factura.ServiceReference1.cargoRequest();
            inValue.Body = new Factura.ServiceReference1.cargoRequestBody();
            inValue.Body.Puesto = Puesto;
            return ((Factura.ServiceReference1.WebService1Soap)(this)).cargoAsync(inValue);
        }
    }
}
